# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Undertow CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  maven_cache:
    name: Build Initial Maven Cache
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: joschi/setup-jdk@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          m2-
    - name: Build Maven Cache
      run: |
        mvn --version
        mvn clean
  build-jdk11:
    runs-on: ubuntu-latest
    needs: maven_cache
    steps:
    - uses: n1hility/cancel-previous-runs@v2
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          m2-
    - name: Set up JDK 1.8
      uses: joschi/setup-jdk@v2
      with:
        java-version: 11
    - name: Build & Test
      run: mvn -U -B -fae -DskipTests '-Dfindbugs' clean install
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.wildfly-version }}
        path: '**/surefire-reports/*.txt'

  test-matrix:
    name: JDK ${{ matrix.jdk }} JVM Tests
    runs-on: ${{ matrix.os }}
    needs: build-jdk11
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        modules: [parser-generator, core, servlet, websockets-jsr]
        jdk: [8. 11]
    steps:
    - uses: n1hility/cancel-previous-runs@v2
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java.name }}
      uses: joschi/setup-jdk@v2
      with:
        java-version: ${{ matrix.jdk}}
    - name: Build & Test
      run: mvn -U -B -fae -Pproxy '-DfailIfNoTests=false' test
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.wildfly-version }}
        path: '**/surefire-reports/*.txt'
